--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-09-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "MLTUTORIALES"."EMPLEADO" 
   (	"CODIGO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"SALARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MLTUTORIALES.EMPLEADO
SET DEFINE OFF;
Insert into MLTUTORIALES.EMPLEADO (CODIGO,NOMBRE,SALARIO) values ('1','Juan','500');
Insert into MLTUTORIALES.EMPLEADO (CODIGO,NOMBRE,SALARIO) values ('2','Anahi','500');
--------------------------------------------------------
--  DDL for Index SYS_C007002
--------------------------------------------------------

  CREATE UNIQUE INDEX "MLTUTORIALES"."SYS_C007002" ON "MLTUTORIALES"."EMPLEADO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "MLTUTORIALES"."EMPLEADO" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MLTUTORIALES"."EMPLEADO" MODIFY ("SALARIO" NOT NULL ENABLE);
  ALTER TABLE "MLTUTORIALES"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MLTUTORIALES"."EMPLEADO" MODIFY ("CODIGO" NOT NULL ENABLE);
